/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Transcription Job */
        post: operations["create_transcription_job_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobResultUrls
         * @description Artifact URLs produced by a successful transcription job.
         */
        JobResultUrls: {
            /** Midi */
            midi: string;
            /** Musicxml */
            musicxml: string;
            /** Pdf */
            pdf: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "done" | "failed";
        /**
         * JobStatusResponse
         * @description Response body for GET /jobs/{job_id}.
         */
        JobStatusResponse: {
            /** Error */
            error?: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Progress */
            progress: number;
            result_urls?: components["schemas"]["JobResultUrls"] | null;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * TranscribeRequest
         * @description Request body for POST /transcribe.
         *
         *     Exactly one of `audio_url` or `audio_file_b64` must be provided.
         */
        TranscribeRequest: {
            /**
             * Audio File B64
             * @description Base64-encoded audio payload (mp3/wav).
             */
            audio_file_b64?: string | null;
            /**
             * Audio Url
             * @description HTTP(S) URL the backend will fetch the audio from.
             */
            audio_url?: string | null;
        };
        /**
         * TranscribeResponse
         * @description Response body for POST /transcribe.
         */
        TranscribeResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** @default pending */
            status: components["schemas"]["JobStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transcription_job_transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscribeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
